server:
  port: 20052
spring:
  application:
    name: system-service
  datasource:
    url: jdbc:mysql:///api?characterEncoding=utf8&useSSL=false&useLocalSessionState=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://39.96.63.222:20050/eureka/
    registry-fetch-interval-seconds: 5

mybatis-plus:
  configuration:
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
    map-underscore-to-camel-case: true
  global-config:
    banner: false
    db-config:
      column-underline: true
      field-strategy: NOT_NULL
      id-type: AUTO
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: com.zzn.boot.*.model